CREATE TABLE IF NOT EXISTS access_logs (
  id BIGSERIAL PRIMARY KEY,
  fecha_hora TIMESTAMP NOT NULL DEFAULT NOW(),
  evento VARCHAR(64) NOT NULL,
  persona VARCHAR(128) NOT NULL,
  distancia DOUBLE PRECISION
);
